// Generated by Wrangler by running `wrangler types --env-interface WorkerEnv src/worker-env.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface WorkerEnv {
}
