name: Fast Forward

on:
  issue_comment:
    types: [created]

jobs:
  fast-forward:
    name: Fast Forward
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: on-error
